In [1]:
import numpy as np

In [2]:
A = np.array([[1,2],
             [3,4]])
B = np.array([[5,6],
              [7,8]])

In [3]:
A

array([[1, 2],
       [3, 4]])

In [4]:
B

array([[5, 6],
       [7, 8]])

In [5]:
A @ B

array([[19, 22],
       [43, 50]])

In [6]:
A_inv = np.linalg.inv(A)
B_inv = np.linalg.inv(B)

In [7]:
A_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [8]:
B_inv

array([[-4. ,  3. ],
       [ 3.5, -2.5]])

In [9]:
A @ A_inv

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [10]:
B @ B_inv

array([[1., 0.],
       [0., 1.]])

In [11]:
foo = np.array([[2,1,1],
                [3,2,1],
                [2,1,2]])

In [12]:
foo

array([[2, 1, 1],
       [3, 2, 1],
       [2, 1, 2]])

In [13]:
foo_inv = np.linalg.inv(foo)

In [14]:
foo_inv

array([[ 3., -1., -1.],
       [-4.,  2.,  1.],
       [-1.,  0.,  1.]])

In [28]:
import numpy as np
b2 = np.array([[3,-3],
               [4,-5]])
b2

array([[ 3, -3],
       [ 4, -5]])

In [27]:
b1 = np.array([[1,0],
               [0, 1]])
b1

array([[1, 0],
       [0, 1]])

In [29]:
M = np.linalg.inv(b2) @ b1
M

array([[ 1.66666667, -1.        ],
       [ 1.33333333, -1.        ]])

In [30]:
M @ np.array([[3],[2]])

array([[3.],
       [2.]])

In [24]:
np.linalg.inv(M) @ np.array([[1],[1]])

array([[1.],
       [0.]])